# 0. Load imports 

In [3]:
## imports
import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt
import seaborn as sns

## print multiple things from same cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## load data on 2020 crimes in DC
df = dc_crim_2020 = pd.read_csv("https://opendata.arcgis.com/datasets/f516e0dd7b614b088ad781b0c4002331_2.csv")

In [4]:
df

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID
0,402374.0,132186.0,10251445,2020/09/11 04:00:00+00,2010/09/02 04:00:00+00,2010/09/02 04:00:00+00,2300 - 2399 BLOCK OF AINGER PLACE SE,HOMICIDE,GUN,MIDNIGHT,...,007502 1,7502.0,Precinct 134,NaN,402374.0,132186.0,38.857483,-76.972648,921212443,NaN
1,397920.0,136943.0,5370,2020/01/17 02:39:05+00,2020/01/11 02:48:51+00,2020/01/17 02:48:54+00,800 - 899 BLOCK OF 9TH STREET NW,THEFT F/AUTO,OTHERS,EVENING,...,005802 5,5802.0,Precinct 129,DOWNTOWN,397920.0,136943.0,38.900337,-77.023979,921212447,NaN
2,402411.0,131808.0,10147537,2020/12/21 05:00:00+00,2010/10/10 02:00:00+00,NaN,2300 - 2499 BLOCK OF HARTFORD STREET SE,HOMICIDE,OTHERS,MIDNIGHT,...,007408 2,7408.0,Precinct 115,NaN,402411.0,131808.0,38.854078,-76.972223,921212449,NaN
3,398389.0,140433.0,20000957,2020/01/02 18:53:05+00,2019/12/30 20:00:20+00,2020/01/02 18:53:32+00,3300 - 3399 BLOCK OF PARK PLACE NW,THEFT/OTHER,OTHERS,DAY,...,003200 3,3200.0,Precinct 38,NaN,398389.0,140433.0,38.931777,-77.018580,921213797,NaN
4,398946.0,139092.0,20001080,2020/01/03 01:55:16+00,2020/01/02 20:39:16+00,2020/01/02 22:20:27+00,2200 - 2299 BLOCK OF 1ST STREET NW,BURGLARY,OTHERS,EVENING,...,003301 1,3301.0,Precinct 135,NaN,398946.0,139092.0,38.919698,-77.012154,921213798,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27927,397241.0,140302.0,20097822,2020/07/06 22:02:48+00,2020/07/06 20:42:59+00,2020/07/06 21:00:41+00,1325 - 1399 BLOCK OF PARK ROAD NW,ASSAULT W/DANGEROUS WEAPON,KNIFE,EVENING,...,002900 2,2900.0,Precinct 41,NaN,397241.0,140302.0,38.930594,-77.031820,921779024,NaN
27928,397328.0,139157.0,20100870,2020/07/13 22:12:52+00,2020/07/07 18:00:45+00,2020/07/07 20:00:57+00,1300 - 1399 BLOCK OF FLORIDA AVENUE NW,THEFT F/AUTO,OTHERS,EVENING,...,004401 2,4401.0,Precinct 22,NaN,397328.0,139157.0,38.920280,-77.030812,921779025,NaN
27929,405049.0,136086.0,20101193,2020/07/14 14:32:30+00,2020/07/11 22:00:31+00,2020/07/14 14:28:59+00,4200 - 4243 BLOCK OF BENNING ROAD NE,THEFT/OTHER,OTHERS,DAY,...,007803 4,7803.0,Precinct 99,NaN,405049.0,136086.0,38.892605,-76.941800,921779026,NaN
27930,399823.0,138853.0,20400676,2020/05/01 18:58:30+00,2020/05/01 15:00:00+00,2020/05/01 15:35:00+00,1948 - 2099 BLOCK OF 3RD STREET NE,THEFT F/AUTO,OTHERS,DAY,...,008702 1,8702.0,Precinct 75,NaN,399823.0,138853.0,38.917546,-77.002041,921779089,NaN


# 1. Questions: list comprehension

- In class example, why did we need the "courses" at the beginning of the list iteration
- How did the join syntax work in the example where we paste together offenses from same ward

In [5]:
## toy example

### pool of courses
all_courses = ["QSS20", "QSS17", "GOV10", "GOV4", "CSC1"]


## 1.1 Application 1: filtering to a smaller list

When we might use: have a lot of columns in a dataframe; want to filter to a smaller set using some pattern

In [6]:
### pull out ones that contain GOV in the string
gov_c = [course for course in all_courses if "GOV" in course]
gov_c # result

['GOV10', 'GOV4']

In [7]:
### showing that the "course" is just a placeholder/
### arbitrary interator
gov_c_alt = [x for x in all_courses if "GOV" in x]

gov_c == gov_c_alt

True

## 1.2 Application two: keep all objects in the list but do some transformation

In [8]:
all_courses

## strip the numbers from the course names
courses_prefix = [x[:3] for x in all_courses]
courses_prefix # could then find unique elements


['QSS20', 'QSS17', 'GOV10', 'GOV4', 'CSC1']

['QSS', 'QSS', 'GOV', 'GOV', 'CSC']

In [9]:
# Join all together example
" #:(# ".join(courses_prefix)

'QSS #:(# QSS #:(# GOV #:(# GOV #:(# CSC'

#### Your turn: Using original list, add "dartmouth_" prefix to the course name

In [23]:
prefix = "dartmouth_"
dartmouth_prefix = [prefix + course for course in all_courses ]
dartmouth_prefix

['dartmouth_QSS20',
 'dartmouth_QSS17',
 'dartmouth_GOV10',
 'dartmouth_GOV4',
 'dartmouth_CSC1']

## 1.3 Subsetting columns

Use list comprehension to filter to columns with id in the string. Then, create a new dataframe called df1 that contains only column heads with "id"

In [25]:
id_cols = [col for col in df.columns if "ID" in col]
id_cols

## Then, filter the data
df[id_cols]

['BID', 'OBJECTID', 'OCTO_RECORD_ID']

,BID,OBJECTID,OCTO_RECORD_ID
0,NaN,921212443,NaN
1,DOWNTOWN,921212447,NaN
2,NaN,921212449,NaN
3,NaN,921213797,NaN
4,NaN,921213798,NaN
...,...,...,...
27927,NaN,921779024,NaN
27928,NaN,921779025,NaN
27929,NaN,921779026,NaN
27930,NaN,921779089,NaN


## 1.4 Comprehension for numbers

Here we compare two ways of creating a list of even numbers.

In [26]:
num_list = np.arange(10000)
num_list

array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

In [27]:
%%time
even_nums = [i for i in num_list if (i % 2) == 0]
even_nums

CPU times: user 1.49 ms, sys: 184 μs, total: 1.67 ms
Wall time: 1.72 ms


[np.int64(0),
 np.int64(2),
 np.int64(4),
 np.int64(6),
 np.int64(8),
 np.int64(10),
 np.int64(12),
 np.int64(14),
 np.int64(16),
 np.int64(18),
 np.int64(20),
 np.int64(22),
 np.int64(24),
 np.int64(26),
 np.int64(28),
 np.int64(30),
 np.int64(32),
 np.int64(34),
 np.int64(36),
 np.int64(38),
 np.int64(40),
 np.int64(42),
 np.int64(44),
 np.int64(46),
 np.int64(48),
 np.int64(50),
 np.int64(52),
 np.int64(54),
 np.int64(56),
 np.int64(58),
 np.int64(60),
 np.int64(62),
 np.int64(64),
 np.int64(66),
 np.int64(68),
 np.int64(70),
 np.int64(72),
 np.int64(74),
 np.int64(76),
 np.int64(78),
 np.int64(80),
 np.int64(82),
 np.int64(84),
 np.int64(86),
 np.int64(88),
 np.int64(90),
 np.int64(92),
 np.int64(94),
 np.int64(96),
 np.int64(98),
 np.int64(100),
 np.int64(102),
 np.int64(104),
 np.int64(106),
 np.int64(108),
 np.int64(110),
 np.int64(112),
 np.int64(114),
 np.int64(116),
 np.int64(118),
 np.int64(120),
 np.int64(122),
 np.int64(124),
 np.int64(126),
 np.int64(128),
 np.int64(130),

In [15]:
%%time
num_list[~(num_list % 2).astype(bool)]

CPU times: user 490 μs, sys: 651 μs, total: 1.14 ms
Wall time: 848 μs


array([   0,    2,    4, ..., 9994, 9996, 9998], shape=(5000,))

In [16]:
num_list[ ~(num_list % 2).astype(bool) ]

array([   0,    2,    4, ..., 9994, 9996, 9998], shape=(5000,))

#### Your turn: Extract all numbers in num_list that end in 7

In [52]:
%%time
ending_in_7 = [n for n in num_list if str(n)[-1] == "7"] #had to make a string to slice
ending_in_7_int = [int(n) for n in ending_in_7]



CPU times: user 5.98 ms, sys: 1.56 ms, total: 7.54 ms
Wall time: 7.49 ms


#### Your turn: Divide each number  in num_list by 2

In [54]:
divide_two = [float(n/2) for n in num_list]
divide_two

[0.0,
 0.5,
 1.0,
 1.5,
 2.0,
 2.5,
 3.0,
 3.5,
 4.0,
 4.5,
 5.0,
 5.5,
 6.0,
 6.5,
 7.0,
 7.5,
 8.0,
 8.5,
 9.0,
 9.5,
 10.0,
 10.5,
 11.0,
 11.5,
 12.0,
 12.5,
 13.0,
 13.5,
 14.0,
 14.5,
 15.0,
 15.5,
 16.0,
 16.5,
 17.0,
 17.5,
 18.0,
 18.5,
 19.0,
 19.5,
 20.0,
 20.5,
 21.0,
 21.5,
 22.0,
 22.5,
 23.0,
 23.5,
 24.0,
 24.5,
 25.0,
 25.5,
 26.0,
 26.5,
 27.0,
 27.5,
 28.0,
 28.5,
 29.0,
 29.5,
 30.0,
 30.5,
 31.0,
 31.5,
 32.0,
 32.5,
 33.0,
 33.5,
 34.0,
 34.5,
 35.0,
 35.5,
 36.0,
 36.5,
 37.0,
 37.5,
 38.0,
 38.5,
 39.0,
 39.5,
 40.0,
 40.5,
 41.0,
 41.5,
 42.0,
 42.5,
 43.0,
 43.5,
 44.0,
 44.5,
 45.0,
 45.5,
 46.0,
 46.5,
 47.0,
 47.5,
 48.0,
 48.5,
 49.0,
 49.5,
 50.0,
 50.5,
 51.0,
 51.5,
 52.0,
 52.5,
 53.0,
 53.5,
 54.0,
 54.5,
 55.0,
 55.5,
 56.0,
 56.5,
 57.0,
 57.5,
 58.0,
 58.5,
 59.0,
 59.5,
 60.0,
 60.5,
 61.0,
 61.5,
 62.0,
 62.5,
 63.0,
 63.5,
 64.0,
 64.5,
 65.0,
 65.5,
 66.0,
 66.5,
 67.0,
 67.5,
 68.0,
 68.5,
 69.0,
 69.5,
 70.0,
 70.5,
 71.0,
 71.5,
 72.0,
 72.5

# 2. Questions: lambda functions

Two questions:

- General syntax (see here for a reference: https://www.w3schools.com/python/python_lambda.asp 
- How they work in the context of aggregations

How is a lambda function different from a "normal" user-defined function (that has the syntax def func_name(arg): etc?

- Operates similarly to normal user-defined functions in that it can take any # of arguments
- Operates differently in that it's an "anonymous" function or a function that we don't explicitly name/save in memory

## 2.1 General syntax for lambda functions

In [48]:
### two pools of courses
socsci = ["QSS20", "QSS17", "GOV10"]
natsci = ["BIO2", "PHYS3"]


## generalize some of the steps
## above into a two-arg function
## that takes the course prefix
## and a list of all courses
def filter_courses(prefix, all_courses):
    rel_courses = [c for c in all_courses if prefix in c]
    return(rel_courses)

### a few applications 
filter_courses(prefix = "QSS", all_courses = socsci)
filter_courses(prefix = "QSS", all_courses = natsci)
filter_courses(prefix = "BIO", all_courses = natsci)

['QSS20', 'QSS17']

[]

['BIO2']

In [49]:
## what's the lambda function version of this
filter_courses_v2 = lambda prefix, all_courses: [c for c in all_courses if prefix in c]
filter_courses_v2(prefix = "BIO", all_courses = natsci)


['BIO2']

## 2.2 using alongside agg

In [ ]:
## use lambda to find modal block in a ward- multiple ways

### way 1: subsetting agg syntex
df.groupby("WARD")["BLOCK"].agg(lambda x: x.mode())

### way 2: dictionary agg syntax
df.groupby("WARD").agg({"BLOCK": lambda x: x.mode()})


#### Your turn: Group by WARD and get the mean and standard deviation (std) of X and Y

In [56]:
df.groupby("WARD")[["X", "Y"]].agg(["mean", "std"])

X                           Y             
               mean          std           mean          std
WARD                                                        
1     397289.867555   624.307287  139648.610621   712.362815
2     396621.067712  1223.488923  137564.793599   595.099248
3     393470.489099  1162.323901  141520.418724  1541.617708
4     397841.637555  1023.793670  143307.153700  1545.603726
5     400915.575468  1297.551690  139152.417438  1416.967174
6     399898.301927   980.505436  136139.856333  1112.374544
7     404563.412110  1626.707129  135648.075402  1388.268228
8     400956.107708  1110.298221  131412.540814  1751.194450

In [57]:
df.groupby("WARD")[['X', 'Y']].agg({lambda x: x.mean(), lambda x: x.std()})

X                           Y             
         <lambda_0>   <lambda_1>     <lambda_0>   <lambda_1>
WARD                                                        
1     397289.867555   624.307287  139648.610621   712.362815
2     396621.067712  1223.488923  137564.793599   595.099248
3     393470.489099  1162.323901  141520.418724  1541.617708
4     397841.637555  1023.793670  143307.153700  1545.603726
5     400915.575468  1297.551690  139152.417438  1416.967174
6     399898.301927   980.505436  136139.856333  1112.374544
7     404563.412110  1626.707129  135648.075402  1388.268228
8     400956.107708  1110.298221  131412.540814  1751.194450

### Random sampling and distance measures

In [ ]:
random_uniform = np.random.rand(5)  # 5 random numbers between 0 and 1
print("Random numbers from uniform distribution:", random_uniform)

random_normal = np.random.randn(5)  # 5 random numbers from a standard normal distribution
print("Random numbers from normal distribution:", random_normal)

In [ ]:
N = 200

sns.kdeplot(np.random.rand(N))

In [ ]:
sns.kdeplot(np.random.randn(N))